version: '3.6'

services:
  duniter:
    environment:
    #- DEBUG_ENTRYPOINT=${DUNITER_DEBUG_ENTRYPOINT:-${DEBUG_ENTRYPOINT:-${DEBUG:-}}}
    - DUNITER_AUTO_SYNC=true
    - DUNITER_SYNC_HOST=${DUNITER_SYNC_HOST:-g1.cgeek.fr:443}
    - DUNITER_BMA_ENABLED=true
    - DUNITER_BMA_IP4=${DUNITER_BMA_IP4:-0.0.0.0}
    - DUNITER_BMA_REMOTE_HOST=${DUNITER_BMA_REMOTE_HOST:-g1.astroport.com}
    - DUNITER_BMA_REMOTE_PORT=${DUNITER_BMA_REMOTE:-443}
    - DUNITER_GVA_ENABLED=true
    - DUNITER_GVA_PATH=gva
    - DUNITER_GVA_PORT=30901
    - DUNITER_GVA_REMOTE_PATH=gva
    - DUNITER_GVA_REMOTE_PORT=443
    - DUNITER_GVA_REMOTE_HOST=${DUNITER_GVA_REMOTE_HOST:-g1.astroport.com}
    - DUNITER_GVA_SUBSCRIPTIONS_PATH=gva-sub
    - DUNITER_GVA_WHITELIST=${DUNITER_GVA_WHITELIST:-127.0.0.1,::1}
    - DUNITER_START_OPTS=${DUNITER_START_OPTS:-direct_webstart}
    - DUNITER_SYNC_OPTS=${DUNITER_SYNC_OPTS:-}
    - DUNITER_WS2P_HOST=${DUNITER_WS2P_HOST:-0.0.0.0}
    - DUNITER_WS2P_PORT=${DUNITER_W2SP_PORT:-20901}
    - DUNITER_WS2P_PUBLIC=${DUNITER_W2SP_PUBLIC:-true}
    - DUNITER_WS2P_REMOTE_HOST=${DUNITER_WS2P_REMOTE_HOST:-g1.astroport.com}
    - DUNITER_WS2P_REMOTE_PATH=${DUNITER_WS2P_REMOTE_PATH:-ws2p}
    - DUNITER_WS2P_REMOTE_PORT=${DUNITER_WS2P_REMOTE_PORT:-443}
    - DUNITER_POW_CPU=0.5
    - DUNITER_POW_NBCORES=1
    - DUNITER_MAX_OLD_SPACE_SIZE=${DUNITER_MAX_OLD_SPACE_SIZE:-8192}
    image: pinidh/duniter:1.8.7
    networks:
    - private
    ports:
    - 0.0.0.0:10901:10901
    - 0.0.0.0:20901:20901
    - 0.0.0.0:30901:30901
    - 0.0.0.0:9220:9220
    restart: unless-stopped
    volumes:
    - data:/var/lib/duniter
    - etc:/etc/duniter

networks:
  private:
    name: ${DOCKER_NETWORK_PRIVATE:-duniter}
  public:
    name: ${DOCKER_NETWORK_PUBLIC:-host}

volumes:
  data:
  etc:
